import "./framework/mobx-config.js";

export {
  App,
  type AppOptions,
  type AppRunTestOptions,
  type AppTestSession,
  TextualApp,
  ValueError,
  type TextualAppProps,
} from "./app/index.js";
export {
  AppBlur,
  AppFocus,
  Message,
  Blur,
  Callback,
  Click,
  CloseMessages,
  Compose,
  CursorPosition,
  DeliveryComplete,
  DeliveryFailed,
  DescendantBlur,
  DescendantFocus,
  Enter,
  ExitApp,
  Focus,
  Hide,
  Idle,
  Key,
  Leave,
  ModeChanged,
  Mount,
  MouseCapture,
  MouseDown,
  MouseMove,
  MouseRelease,
  MouseScrollDown,
  MouseScrollLeft,
  MouseScrollRight,
  MouseScrollUp,
  MouseUp,
  Notify,
  Paste,
  Print,
  Ready,
  Resize,
  ScreenResume,
  ScreenSuspend,
  ScrollEvent,
  Show,
  TextSelected,
  Timer,
  Unmount,
  type MessageConstructor,
  type MessageInit,
  type TextSelectionEndpoint,
  type TextSelectionRange,
} from "./events/index.js";
export {
  ActionError,
  BindingError,
  BindingsMap,
  InvalidBinding,
  NoBinding,
  SkipAction,
  makeBindings,
  matchesBindingKey,
  normalizeBindingKey,
  parseAction,
  type ActionNamespace,
  type Binding,
  type BindingDeclaration,
  type ParsedAction,
} from "./bindings/index.js";
export { clamp, Offset, Region, Size, Spacing } from "./geometry/index.js";
export {
  Content,
  Segment,
  Style,
  StyledText,
  Strip,
  type ContentFromTextOptions,
  type ContentInput,
  type ContentPart,
  type ContentTruncateOptions,
  type Span,
  measureVisual,
  renderContent,
  renderVisual,
  resolveVisualRenderWidth,
  visualize,
  type Visual,
  type VisualInput,
  type VisualMeasurement,
  type VisualizeOptions,
} from "./content/index.js";
export {
  type ActiveBinding,
  ActiveModeError,
  type ResolvedTitle,
  type TitleOverride,
  type AppDriver,
  type ActionTargetDescriptor,
  type AnimationLevel,
  BadWidgetName,
  BadIdentifier,
  type BindingClash,
  type BindingNamespace,
  DeclarationError,
  DuplicateIds,
  DuplicateKeyHandlers,
  InvalidModeError,
  MountError,
  type KeymapInput,
  type MessageSubscriber,
  type NotifyOptions,
  type PointerShape,
  OnDecoratorError,
  ScreenStackError,
  type SimpleCommand,
  StylesheetError,
  SuspendNotSupported,
  TextualProvider,
  UnknownModeError,
  Widget,
  WidgetHost,
  WidgetRegistry,
  find_first_enabled,
  find_last_enabled,
  find_next_enabled,
  find_next_enabled_no_wrap,
  formatKey,
  get_directed_distance,
  getKeyDisplay,
  keyToCharacter,
  on,
  useBindings,
  useResolvedTitle,
  useTextual,
  useTimer,
  useWorker,
  useWidget,
  type OnOptions,
  type RegisterWidgetOptions,
  type RegisterWidgetTypeOptions,
  type ScreenDescriptor,
  type Screen,
  type ScreenOptions,
  type SystemCommand,
  type SystemCommandResolver,
  type UseWidgetOptions,
  type UseWidgetResult,
  type WidgetActionCallback,
  type WidgetActions,
  type WidgetCheckAction,
  type WidgetHandlers,
  type WidgetHostProps,
  type WidgetIdentity,
  type WidgetMessageHandler,
  type WidgetOptions,
  type WidgetTypeMetadata,
  WidgetError,
  type EnabledCandidate,
  type ScrollAnimationState,
  type ScrollToOptions,
} from "./framework/index.js";
export {
  NodeList,
  DOMQuery,
  NoMatches,
  TooManyMatches,
  WrongType,
  StylesReader,
  MeasuredSizeReader,
  type MeasuredSize,
  type MeasuredSizeReaderProps,
  WidgetScope,
  useCurrentWidget,
  useStyles,
} from "./framework/index.js";
export {
  Notification,
  Notifications,
  type NotificationContent,
  type NotificationInit,
  type NotificationSeverity,
} from "./services/notifications.js";
export { RLock } from "./services/concurrency.js";
export {
  UnsupportedUrlScheme,
  parseOpenableUrl,
  runUrlOpenCommand,
  spawnUrlOpener,
  urlOpenCommand,
  type UrlOpenCommand,
  type UrlOpener,
} from "./services/url-opener.js";
export { Signal, SignalError, type SignalCallback } from "./services/signal.js";
export {
  ANSI_THEME_DARK,
  ANSI_THEME_LIGHT,
  BUILTIN_THEMES,
  ThemeManager,
  type ActiveTheme,
  type AnsiTheme,
  type ThemeDefinition,
} from "./services/theme.js";
export {
  _get_environ_bool,
  _get_environ_int,
  _get_environ_port,
  getEnvironBool,
  getEnvironInt,
  getEnvironPort,
  parseTextualFeatures,
  type EnvironmentMap,
  type TextualFeatureState,
} from "./services/environment.js";
export { ManagedTimer, type TimerOptions } from "./services/timer.js";
export {
  DeadlockError,
  NoActiveWorker,
  Worker,
  WorkerCancelled,
  WorkerDeclarationError,
  WorkerError,
  WorkerFailed,
  WorkerManager,
  WorkerStateChanged,
  getCurrentWorker,
  get_current_worker,
  work,
  type WorkerCallable,
  type WorkerDescription,
  type WorkerOwner,
  type WorkFunction,
  type WorkDecoratorOptions,
  type WorkerOptions,
  type WorkerState,
} from "./services/worker.js";
export { RuntimeError, getActiveMessagePump } from "./services/concurrency.js";
// [LAW:one-source-of-truth] MobX is the project's only reactive model; it is used
// directly by AppRuntime, Widget, and services. No parallel reactive
// abstraction is exported.
export {
  combineBorderQuads,
  Color,
  ColorParseError,
  Gradient,
  lab_to_rgb,
  Scalar,
  StyleValueError,
  Styles,
  StylesCache,
  StylesheetParseError,
  UnexpectedEnd,
  Unit,
  UnresolvedVariableError,
  align_help_text,
  color_property_help_text,
  generateTcss,
  InvalidQueryFormat,
  labToRgb,
  normalizeColor,
  normalizeScalar,
  parseScalar,
  parseSelectorList,
  parseTcss,
  scalar_help_text,
  spacing_invalid_value_help_text,
  rgb_to_lab,
  renderBorderLabel,
  renderBorderRow,
  rgbToLab,
  scalarToInkValue,
  type BorderQuad,
  type BorderValue,
  type BorderRowGlyphs,
  type HslColor,
  type HsvColor,
  type Lab,
  type ParsedDeclaration,
  type ParsedRule,
  type ParsedSelector,
  type ParsedSelectorSegment,
  type ParsedStylesheet,
  type RenderBorderLabelOptions,
  type SelectorSpecificity,
  type AlignValue,
  type OffsetValue,
  type OverflowValue,
  type ScrollbarGutterValue,
  type TextStyleValue,
  Stylesheet,
  Token,
  TokenError,
  colorToInkValue,
  isIdSelector,
  is_id_selector,
  normalizeStyleAssignment,
  substituteReferences,
  substitute_references,
  tokenizeTcss,
  tokenize_tcss,
} from "./styles/index.js";
export {
  Failure,
  FunctionValidator,
  InputValidationController,
  IntegerValidator,
  LengthValidator,
  NumberValidator,
  RegexValidator,
  URLValidator,
  ValidationResult,
  Validator,
  normalizeValidateOn,
  type ValidationFailure,
  type ValidationFailureInit,
  type ValidationText,
  type ValidateOn,
} from "./validation/index.js";
export {
  SuggestFromList,
  SuggestionController,
  SuggestionReady,
  Suggester,
} from "./suggestions/index.js";
export {
  CommandPalette,
  CommandPaletteClosed,
  CommandPaletteOpened,
  CommandPaletteOptionHighlighted,
  CommandPaletteScreen,
  DiscoveryHit,
  Hit,
  Provider,
  SimpleCommandProvider,
  SystemCommandsProvider,
  type CommandHit,
  type CommandHitInit,
  type CommandPaletteOptions,
  type CommandPaletteScreenProps,
  type DiscoveryHitInit,
  type PaletteResult,
  type ProviderConstructor,
  type ProviderContext,
} from "./commands/index.js";
export {
  OutOfBounds,
  Pilot,
  PilotTargetNotFound,
  camelToSnake,
  runTest,
  type RunTestOptions,
  type TestSession,
} from "./testing/index.js";
export {
  Button,
  ButtonPressed,
  Checkbox,
  Footer,
  FooterKey,
  Header,
  Input,
  InputChanged,
  InputSubmitted,
  InvalidLineStyle,
  InvalidRuleOrientation,
  Label,
  Link,
  ProgressBar,
  RadioButton,
  RadioSet,
  RadioSetChanged,
  Rule,
  Sparkline,
  Static,
  summaryMax,
  summaryMin,
  Switch,
  SwitchChanged,
  ToggleChanged,
  type ButtonProps,
  type ButtonVariant,
  type CheckboxProps,
  type FooterKeyProps,
  type FooterProps,
  type HeaderProps,
  type InputProps,
  type InputHandle,
  type LabelProps,
  type LinkProps,
  type ProgressBarProps,
  type RadioButtonProps,
  type RadioSetButtonSpec,
  type RadioSetProps,
  type RuleOrientation,
  type RuleProps,
  type SparklineProps,
  type SparklineSummaryName,
  type StaticProps,
  type SummaryFunction,
  type SwitchProps,
} from "./widgets/index.js";
